<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicle Report - {{ $vehicle->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 12px; }
        h1 { color: #2563eb; margin-bottom: 4px; }
        .meta { color: #64748b; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #e2e8f0; padding: 8px; text-align: left; }
        th { background: #f1f5f9; }
        .total { font-weight: bold; color: #2563eb; }
    </style>
</head>
<body>
    <h1>{{ $vehicle->name }}</h1>
    <p class="meta">{{ $vehicle->make }} {{ $vehicle->model }} · {{ $vehicle->number_plate }} · {{ $vehicle->year }}</p>
    <p><strong>Owner:</strong> {{ $vehicle->user->name ?? 'N/A' }} · <strong>Mileage:</strong> {{ number_format($vehicle->mileage) }}</p>
    <p><strong>Total maintenance:</strong> <span class="total">${{ number_format($totalCost, 2) }}</span></p>
    <table>
        <thead>
            <tr><th>Date</th><th>Service</th><th>Provider</th><th>Cost</th></tr>
        </thead>
        <tbody>
            @foreach($vehicle->serviceRecords as $service)
            <tr>
                <td>{{ $service->service_date->format('Y-m-d') }}</td>
                <td>{{ $service->service_type }}</td>
                <td>{{ $service->service_provider }}</td>
                <td>${{ number_format($service->cost, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <p style="margin-top:24px;font-size:10px;color:#94a3b8;">Generated by VehiclePro · {{ now()->format('M d, Y H:i') }}</p>
</body>
</html>
